Chpater08_API 응답 통일 & 에러 핸들러
SSUMC-6th/Spring_Boot_C pull request #34
Opened 2024-06-12 07:45 UTC by qzzloz

## #️⃣ 연관된 이슈

- #29 
<br>

## ✅ 워크북 체크리스트

- [x] 모든 핵심 키워드 정리를 마쳤나요?
- [ ] 핵심 키워드에 대해 완벽히 이해하셨나요?
- [x] 이론 학습 이후 직접 실습을 해보는 시간을 가졌나요?
- [x] 미션을 수행하셨나요?
- [ ] 미션을 기록하셨나요?
<br>

## ✅ 컨벤션 체크리스트

- [x] 디렉토리 구조 컨벤션을 잘 지켰나요?
- [x] pr 제목을 컨벤션에 맞게 작성하였나요?
- [x] pr에 해당되는 이슈를 연결하였나요?
- [x] 적절한 라벨을 설정하였나요?
- [x] 스터디원들에게 code review를 요청하기 위해 reviewer를 등록하였나요?
- [x] 닉네임/main 브랜치의 최신 상태를 반영하고 있는지 확인했나요?
<br>

## 📌 주안점

2024-06-12 08:23 UTC, ryogaeng approved these changes
시험기간임에도 불구하고 고생하셨습니다!

2024-06-17 07:39 UTC, Gusionling approved these changes

2024-06-17 18:11 UTC, chaeyeon0130 requested changes
밍님!! 시험기간인데도 8주차 키워드 잘 정리해주셔서 감사합니다💓
호옥시 미션 수행 내용은 어디서 확인하면 되는 걸까요..?🤩

2024-06-18 03:26 UTC, qzzloz commented
> 밍님!! 시험기간인데도 8주차 키워드 잘 정리해주셔서 감사합니다💓 호옥시 미션 수행 내용은 어디서 확인하면 되는 걸까요..?🤩

노션에 추가하는 걸 깜빡했습니다ㅠㅠ 방금 깃허브 링크와 스크린샷 추가했습니다!

2024-06-23 06:49 UTC, chaeyeon0130 approved these changes
수고하셨습니다!!💓

2024-06-23 13:18 UTC, merged